EPOCHS: 5
BATCH_SIZE: 32
LEARNING_RATE: 0.001
FEATURES_SIZE: 6 # Number of node features in your HIV dataset
EMBEDDING_SIZE: 1024
CLASSES: 2 # Number of classes for classification (e.g., active vs inactive)